### ISSUE TITLE
Deffect with comments removing

### ISSUE THREAD

**Issue by trelatomasz** [pelme/django-compress#2]
I added script containg comment such as:

/*******************************************************************************
 jquery.mb.components
 Copyright (c) 2001-2010. Matteo Bicocchi (Pupunzi); Open lab srl, Firenze - Italy
 email: info@pupunzi.com
 site: http://pupunzi.com

 Licences: MIT, GPL
 http://www.opensource.org/licenses/mit-license.php
 http://www.gnu.org/licenses/gpl.html
 ******************************************************************************/

The output contains partial comment:

jquery.mb.components
Copyright(c)2001-2010.Matteo Bicocchi(Pupunzi);Open lab srl,Firenze-Italy
email:info@pupunzi.com
site:http:Licences:MIT,GPL
http:http:******************************************************************************/

I tested version checkouted from git

6f400b9f26fde8308345099287f213826805d1e7
master HEAD as of 2009-12-14

Using OS X 10.4, python 2.6

I suppose this is a bug. Shouldn't comments be removed completely?

**Comment by cyberdelia** [comment]
Which filter do you use ?!

**Comment by pelme** [comment]
As you might have noticed, django-compress has not been updated in a long time.

I will not continue to maintain it in the future, I suggest you check out cyberdelias django-pipeline fork instead!

This might be fixed in django-pipeline, if not, please open an issue there instead!

Sorry for the inconvenience!
